from pdt.models import Project, Phase, Iteration, ActivityTime, DefectData, Developer, Manager, Metrics
pr1 = Project(name="Test Project1", description="2 phases", project_id=1)
pr2 = Project(name="Test Project2", description="0 phases", project_id=2)
pr1.save()
pr2.save()


ph1 = Phase(project_id = 1, phase_id = 1, num_of_iteration = 2)
ph2 = Phase(project_id = 1, phase_id = 2, num_of_iteration = 2)
ph3 = Phase(project_id = 1, phase_id = 3, num_of_iteration = 3)
ph4 = Phase(project_id = 1, phase_id = 4, num_of_iteration = 3)
ph1.save()
ph2.save()
ph3.save()
ph4.save()

it1 = Iteration(phase = ph1, iteration_id = 1, code_size = 111)
it2 = Iteration(phase = ph1, iteration_id = 2, code_size = 222)
it3 = Iteration(phase = ph2, iteration_id = 1, code_size = 333)
it4 = Iteration(phase = ph2, iteration_id = 2, code_size = 555)
it5 = Iteration(phase = ph3, iteration_id = 1, code_size = 111)
it6 = Iteration(phase = ph3, iteration_id = 2, code_size = 222)
it7 = Iteration(phase = ph3, iteration_id = 3, code_size = 333)
it8 = Iteration(phase = ph4, iteration_id = 1, code_size = 333)
it9 = Iteration(phase = ph4, iteration_id = 2, code_size = 333)
it10 = Iteration(phase = ph4, iteration_id = 3, code_size = 333)
it1.save()
it2.save()
it3.save()
it4.save()
it5.save()
it6.save()
it7.save()
it8.save()
it9.save()
it10.save()

pr1.current_ite = it5
pr1.save()

dr1 = Developer(employee_id = 1, name = "Muzzy")
dr1.save()
dr1.projects.add(pr1,pr2)
dr2 = Developer(employee_id = 2, name = "Ethern")
dr2.save()
dr2.projects.add(pr1,pr2)
dr3 = Developer(employee_id = 3, name = "Johnson")
dr3.save()
dr3.projects.add(pr1)

dd11 = DefectData(data_type = 'R', inject_iteration = it1, remove_iteration = it2, developer = dr1)
dd12 = DefectData(data_type = 'D', inject_iteration = it1, remove_iteration = it2, developer = dr1)
dd13 = DefectData(data_type = 'I', inject_iteration = it1, remove_iteration = it1, developer = dr1)
dd21 = DefectData(data_type = 'B', inject_iteration = it2, remove_iteration = it2, developer = dr2)
dd22 = DefectData(data_type = 'R', inject_iteration = it2, remove_iteration = it2, developer = dr2)

dd33 = DefectData(data_type = 'B', inject_iteration = it3, remove_iteration = it4, developer = dr1)
dd34 = DefectData(data_type = 'I', inject_iteration = it3, remove_iteration = it4, developer = dr2)
dd44 = DefectData(data_type = 'I', inject_iteration = it4, remove_iteration = it4, developer = dr2)
dd11.save()
dd12.save()
dd13.save()
dd21.save()
dd22.save()
dd33.save()
dd34.save()
dd44.save()

a1 = ActivityTime(iteration = it1, name = "Development", time_used = 60000, developer = dr1)
a2 = ActivityTime(iteration = it1, name = "Management", time_used = 40000, developer = dr1)
a3 = ActivityTime(iteration = it1, name = "Defect Removal", time_used = 33000, developer = dr1)
a4 = ActivityTime(iteration = it2, name = "Management", time_used = 33333, developer = dr1)
a5 = ActivityTime(iteration = it2, name = "Development", time_used = 60000, developer = dr1)
a6 = ActivityTime(iteration = it2, name = "Defect Removal", time_used = 33333, developer = dr1)
a7 = ActivityTime(iteration = it3, name = "Management", time_used = 60000, developer = dr1)
a8 = ActivityTime(iteration = it3, name = "Development", time_used = 60000, developer = dr1)
a9 = ActivityTime(iteration = it3, name = "Defect Removal", time_used = 33333, developer = dr1)
a10 = ActivityTime(iteration = it4, name = "Management", time_used = 60000, developer = dr1)
a11 = ActivityTime(iteration = it4, name = "Development", time_used = 33333, developer = dr1)
a12 = ActivityTime(iteration = it4, name = "Defect Removal", time_used = 33333, developer = dr1)
a13 = ActivityTime(iteration = it5, name = "Development", time_used = 33333, developer = dr1)
a14 = ActivityTime(iteration = it5, name = "Management", time_used = 60000, developer = dr1)
a15 = ActivityTime(iteration = it5, name = "Defect Removal", time_used = 60000, developer = dr1)
a1.save()
a2.save()
a3.save()
a4.save()
a5.save()
a6.save()
a7.save()
a8.save()
a9.save()
a10.save()
a11.save()
a12.save()
a13.save()
a14.save()
a15.save()










pr3 = Project(name="Test Project3 (closed)", description="all completed", project_id=3)
pr3.save()


ph1 = Phase(project_id = 1, phase_id = 1, num_of_iteration = 2)
ph2 = Phase(project_id = 1, phase_id = 2, num_of_iteration = 2)
ph3 = Phase(project_id = 1, phase_id = 3, num_of_iteration = 3)
ph4 = Phase(project_id = 1, phase_id = 4, num_of_iteration = 3)
ph1.save()
ph2.save()
ph3.save()
ph4.save()

it1 = Iteration(phase = ph1, iteration_id = 1, code_size = 111)
it2 = Iteration(phase = ph1, iteration_id = 2, code_size = 222)
it3 = Iteration(phase = ph2, iteration_id = 1, code_size = 333)
it4 = Iteration(phase = ph2, iteration_id = 2, code_size = 555)
it5 = Iteration(phase = ph3, iteration_id = 1, code_size = 111)
it6 = Iteration(phase = ph3, iteration_id = 2, code_size = 222)
it7 = Iteration(phase = ph3, iteration_id = 3, code_size = 333)
it8 = Iteration(phase = ph4, iteration_id = 1, code_size = 333)
it9 = Iteration(phase = ph4, iteration_id = 2, code_size = 333)
it10 = Iteration(phase = ph4, iteration_id = 3, code_size = 333)
it1.save()
it2.save()
it3.save()
it4.save()
it5.save()
it6.save()
it7.save()
it8.save()
it9.save()
it10.save()

pr3.current_ite = it10
pr3.save()

dr1 = Developer(employee_id = 5, name = "Somebody")
dr1.projects.add(pr3)
dr1.save()
dr2 = Developer(employee_id = 6, name = "Another")
dr2.projects.add(pr3)
dr2.save()

dd11 = DefectData(data_type = 'R', inject_iteration = it1, remove_iteration = it2, developer = dr1)
dd12 = DefectData(data_type = 'D', inject_iteration = it1, remove_iteration = it2, developer = dr1)
dd13 = DefectData(data_type = 'I', inject_iteration = it1, remove_iteration = it1, developer = dr1)
dd21 = DefectData(data_type = 'B', inject_iteration = it2, remove_iteration = it2, developer = dr2)
dd22 = DefectData(data_type = 'R', inject_iteration = it2, remove_iteration = it2, developer = dr2)
dd33 = DefectData(data_type = 'B', inject_iteration = it3, remove_iteration = it4, developer = dr1)
dd34 = DefectData(data_type = 'I', inject_iteration = it3, remove_iteration = it4, developer = dr2)
dd44 = DefectData(data_type = 'I', inject_iteration = it4, remove_iteration = it4, developer = dr2)
dd11.save()
dd12.save()
dd13.save()
dd21.save()
dd22.save()
dd33.save()
dd34.save()
dd44.save()

a1 = ActivityTime(iteration = it1, name = "Development", time_used = 100, developer = dr1)
a2 = ActivityTime(iteration = it1, name = "Management", time_used = 100, developer = dr1)
a3 = ActivityTime(iteration = it1, name = "Defect Removal", time_used = 100, developer = dr1)
a4 = ActivityTime(iteration = it2, name = "Management", time_used = 100, developer = dr1)
a5 = ActivityTime(iteration = it2, name = "Development", time_used = 100, developer = dr1)
a6 = ActivityTime(iteration = it2, name = "Defect Removal", time_used = 100, developer = dr1)
a7 = ActivityTime(iteration = it3, name = "Management", time_used = 100, developer = dr1)
a8 = ActivityTime(iteration = it3, name = "Development", time_used = 100, developer = dr1)
a9 = ActivityTime(iteration = it3, name = "Defect Removal", time_used = 100, developer = dr1)
a10 = ActivityTime(iteration = it4, name = "Management", time_used = 100, developer = dr1)
a11 = ActivityTime(iteration = it4, name = "Development", time_used = 100, developer = dr1)
a12 = ActivityTime(iteration = it4, name = "Defect Removal", time_used = 100, developer = dr1)
a13 = ActivityTime(iteration = it5, name = "Development", time_used = 100, developer = dr1)
a14 = ActivityTime(iteration = it5, name = "Management", time_used = 100, developer = dr1)
a15 = ActivityTime(iteration = it5, name = "Defect Removal", time_used = 100, developer = dr1)
a16 = ActivityTime(iteration = it6, name = "Development", time_used = 100, developer = dr1)
a17 = ActivityTime(iteration = it6, name = "Management", time_used = 100, developer = dr1)
a18 = ActivityTime(iteration = it6, name = "Defect Removal", time_used = 100, developer = dr1)
a19 = ActivityTime(iteration = it7, name = "Development", time_used = 100, developer = dr1)
a20 = ActivityTime(iteration = it7, name = "Management", time_used = 100, developer = dr1)
a21 = ActivityTime(iteration = it7, name = "Defect Removal", time_used = 100, developer = dr1)
a22 = ActivityTime(iteration = it8, name = "Development", time_used = 100, developer = dr1)
a23 = ActivityTime(iteration = it8, name = "Management", time_used = 100, developer = dr1)
a24 = ActivityTime(iteration = it8, name = "Defect Removal", time_used = 100, developer = dr1)
a25 = ActivityTime(iteration = it9, name = "Development", time_used = 100, developer = dr1)
a26 = ActivityTime(iteration = it9, name = "Management", time_used = 100, developer = dr1)
a27 = ActivityTime(iteration = it9, name = "Defect Removal", time_used = 100, developer = dr1)
a28 = ActivityTime(iteration = it10, name = "Development", time_used = 100, developer = dr1)
a29 = ActivityTime(iteration = it10, name = "Management", time_used = 100, developer = dr1)
a30 = ActivityTime(iteration = it10, name = "Defect Removal", time_used = 100, developer = dr1)
a1.save()
a2.save()
a3.save()
a4.save()
a5.save()
a6.save()
a7.save()
a8.save()
a9.save()
a10.save()
a11.save()
a12.save()
a13.save()
a14.save()
a15.save()
a16.save()
a17.save()
a18.save()
a19.save()
a20.save()
a21.save()
a22.save()
a23.save()
a24.save()
a25.save()
a26.save()
a27.save()
a28.save()
a29.save()
a30.save()

